image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - docker info

stages:
  - build

variables:
  CONTAINER_IMAGE: zackartz/artemis:${CI_COMMIT_SHORT_SHA}
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375

build:
  stage: build
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} zackartz/artemis:latest
    - docker push ${CONTAINER_IMAGE}