image: archlinux:latest

stages:
  - build

variables:
  CONTAINER_IMAGE: sanderknape/go-hello-world:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - pacman --confirm -Syu docker
    - systemctl start docker
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} zackartz/artemis:latest
    - docker push ${CONTAINER_IMAGE}