image: debian:latest

stages:
  - build

variables:
  CONTAINER_IMAGE: sanderknape/go-hello-world:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - apt-get update -y
    - apt-get upgrade -y
    - apt-get install docker -y
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} zackartz/artemis:latest
    - docker push ${CONTAINER_IMAGE}