name: Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v1
      with:
        name: Artemis
        path: build/libs/Artemis-1.0-SNAPSHOT-all.jar
  dockerize:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "zackartz/Artemis"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
